if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
  message(FATAL_ERROR "EmbedSpirv needs INPUT, OUTPUT, and SYMBOL")
endif()
file(READ "${INPUT}" spirvBytes HEX)
string(LENGTH "${spirvBytes}" byteLength)
math(EXPR remainder "${byteLength} % 8")
if(NOT remainder EQUAL 0)
  message(FATAL_ERROR "SPIR-V must contain complete 32-bit words")
endif()
set(header "#pragma once\n#include <cstdint>\nnamespace Aster::Shaders\n{\ninline constexpr uint32_t ${SYMBOL}[] = {\n")
math(EXPR lastWord "${byteLength} - 8")
foreach(offset RANGE 0 ${lastWord} 8)
  string(SUBSTRING "${spirvBytes}" ${offset} 8 word)
  string(SUBSTRING "${word}" 0 2 a)
  string(SUBSTRING "${word}" 2 2 b)
  string(SUBSTRING "${word}" 4 2 c)
  string(SUBSTRING "${word}" 6 2 d)
  string(APPEND header "0x${d}${c}${b}${a}u,\n")
endforeach()
string(APPEND header "};\n}\n")
file(WRITE "${OUTPUT}" "${header}")
